create table ADM_USERS(USER_ID bigint auto_increment, USER_NAME varchar(255),PASSWORD varchar(255),ADMIN INT,CREATION_DATE TIMESTAMP,LAST_LOGIN_DATE DATE);

create table TX_CONTACTS(CONTACT_ID bigint auto_increment, NAME varchar(255),EMAIL varchar(255),PHONE_NUMBER INT,CREATION_DATE TIMESTAMP,LAST_MODIFIED_DATE DATE);